name: weather_app_clean_code_architecture
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  geolocator: ^14.0.2
  shared_preferences: ^2.5.3
  http: ^1.5.0
  internet_connection_checker: ^0.0.1+3
  equatable: ^2.0.7
  dartz: ^0.10.1
  get_it: ^8.0.3
  flutter_bloc: ^9.1.0
  flutter_screenutil: ^5.9.3
  easy_localization: ^3.0.7
  flutter_native_splash: ^2.3.9
  location: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/images/images.jpg"
    min_sdk_android: 21

flutter_lints: ^4.0.0



flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lang/

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  android: true
  ios: true
  fullscreen: true
